on: 
  push:
    branches:
      - build

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: release_build 
        run: |
          pwd
          ls
          sudo apt-get install dvipng dvisvgm
          pip install -r requirements.txt
          make gh-release
 